# Generated by Django 3.1.1 on 2020-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('objective', models.TextField(default='')),
                ('city', models.CharField(default='-', max_length=30)),
                ('country', models.CharField(default='-', max_length=30)),
                ('pincode', models.CharField(default='-', max_length=30)),
                ('phn', models.CharField(default='contact number', max_length=30)),
                ('add', models.CharField(default='Address here', max_length=500)),
                ('eml', models.CharField(default='Your Email here', max_length=100)),
            ],
        ),
    ]
