# Generated by Django 3.1.1 on 2020-12-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumecreate', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='personal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resumecreate.personal'),
        ),
    ]
