# Generated by Django 3.1.1 on 2020-11-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='subject',
            new_name='phone',
        ),
    ]
