# Generated by Django 3.1.1 on 2020-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('abouttxt', models.TextField(default='')),
                ('fb', models.CharField(default='FaceBook', max_length=30)),
                ('lkdn', models.CharField(default='LinkdIn', max_length=30)),
                ('tw', models.CharField(default='Twitter', max_length=30)),
                ('insta', models.CharField(default='Insta', max_length=30)),
                ('tell', models.CharField(default='contact number', max_length=30)),
                ('add', models.CharField(default='Address here', max_length=500)),
                ('eml', models.CharField(default='Your Email here', max_length=100)),
                ('set_name', models.CharField(default='setting', max_length=30)),
            ],
        ),
    ]
